layout_spectrum: 0.1340114
name: Kathy Burke
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8389544
  lightness: 0.1290051
  saturation: 0.1543002
  rhythmicContrast: 0.06523847
  brandColors:
    - '#162017'
    - '#4A6728'
    - '#E9EAF1'
    - '#9BB4D8'
    - '#BDCD27'
typography_spectrum: 0.5
