layout_spectrum: 0.1340114
typography_spectrum: 0
color:
  lightness: 0.7257472
  brandStrength: 0.8389544
  saturation: 0.853069
  rhythmicContrast: 0.06523847
  brandColors:
    - '#162017'
    - '#4A6728'
    - '#E9EAF1'
    - '#9BB4D8'
    - '#BDCD27'
name: Kathy Burke
